version: '3.7'
services:
  deconcentrator:
    build: .
    container_name: deconcentrator
    restart: unless-stopped
    ports:
      - 8338:8338
    environment:
      - RASA_ENDPOINT

networks:
  default:
    external:
      name: beuthbot_network